In [2]:
import numpy as np

D = np.diag([2, 3])
print(D)

v = np.array([1, 1])
print(D @ v)  # [2, 3] <- har o'q cho'ziladi.

[[2 0]
 [0 3]]
[2 3]


In [ ]:
D = np.diag([4, 0.5])
v = [2, 6]

print(D @ v)
np.eye(3)

[8. 3.]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
I = np.eye(3)
print(I) # diagnali 1, qolgani 0

A = np.array([[5, 2, 1],
              [0, 3, 4],
              [1, 1, 2]])
print(np.allclose(A @ I, A)) # true
# A ni I ga ko'paytirdik -> A o'zi qoldi

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
True


In [ ]:
I = np.eye(2)
A = np.eye(4)
print(A)
print(I)

B = [[1, 2],
     [3, 4]]
print(np.allclose(B @ I, B))
print(np.allclose(I @ B, B))

print(2*I @ B)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]]
True
True
[[2. 4.]
 [6. 8.]]


In [ ]:
A = np.array([[3, 2],
              [4, 3]])
print(np.linalg.det(A))
A_inv = np.linalg.inv(A)
print(A_inv)
print(np.around(A @ A_inv))

1.0
[[ 3. -2.]
 [-4.  3.]]
[[1. 0.]
 [0. 1.]]


In [ ]:
A = [[3, 2], [1, 4]]
B = [[2, 6], [1, 3]]
print(np.linalg.det(A))
print(np.linalg.det(B))

# B_inv = np.linalg.inv(B)
A_inv = np.linalg.inv(A)
print(A_inv)

10.000000000000002
0.0
[[ 0.4 -0.2]
 [-0.1  0.3]]


In [6]:
import numpy as np

def checkInv(A):
    a = np.linalg.det(A)
    if np.isclose(a, 0) or A.shape[0] != A.shape[1]: # Use np.isclose for robust comparison with zero
        print(f"Determinant nolga teng bo'lishi mumkin emas! Determinant: {a}")
        return None # Return None when inverse doesn't exist
    else:
        return np.linalg.inv(A)

A = np.array([[3, 2], [6, 4]])
A_inv_result_A = checkInv(A)
# No need to print A_inv_result_A here as the function prints the message

B = np.array([[1, 2], [3, 4]])
A_inv_result_B = checkInv(B)
print(A_inv_result_B)

# Only perform matrix multiplication if an inverse was returned
if A_inv_result_A is not None:
    print(np.allclose(A @ A_inv_result_A, np.eye(A.shape[0])))
else:
    print("Cannot check np.allclose for A, as its inverse does not exist.")

Determinant nolga teng bo'lishi mumkin emas! Determinant: 0.0
[[-2.   1. ]
 [ 1.5 -0.5]]
Cannot check np.allclose for A, as its inverse does not exist.
