In [14]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f"vektorlarni qo'shish: {a + b}")
print(f"vektorlarni ayirish: {a - b}")
print(f"a vektorning norm(yani uzunligi): {np.linalg.norm(a)}")
print(f"b vektorning norm(yani uzunligi): {np.linalg.norm(b)}")
print(f"vektorlar uchun dot product: {np.dot(a, b)}")

vektorlarni qo'shish: [5 7 9]
vektorlarni ayirish: [-3 -3 -3]
a vektorning norm(yani uzunligi): 3.7416573867739413
b vektorning norm(yani uzunligi): 8.774964387392123
vektorlar uchun dot product: 32


In [4]:
import numpy as np

A = np.array([5, 1, 0])
B = np.array([4, 2, 0])
C = np.array([0, 1, 5])

def cos_sim(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

print("A-B:", cos_sim(A, B))
# a-b juda o'xshash, 0.964 chiqdi.

print("A-C:", cos_sim(A, C))
# a-c deyarli o'xshash emas, 0.038 chiqdi.

print("B-C:", cos_sim(B, C))
# b-c deyarli o'xshash emas, 0.087 chiqdi.

A-B: 0.9647638212377322
A-C: 0.038461538461538464
B-C: 0.08770580193070293


In [9]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
B = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

print(A.shape)
print(B.shape)
# buni natijasi (3, 2) (2, 3) chiqdi, ya'ni ikkita matritsani ko'paytirsa bo'ladi. natijada (3x3) matritsa hosil bo'lsihi aniq bo'ldi.
C = A @ B
print(C)
print(C.shape)  # buni natijasi (3, 3 chiqdi)


(3, 2)
(2, 3)
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
(3, 3)


In [13]:
import numpy as np

X = np.array([
    [60, 2],
    [80, 3],
    [100, 3],
    [120, 4],
    [150, 5]
])

# 1 m² = 10 mln so'm
# 1 xona = 20 mln so'm
w = np.array([10, 20])

# Bazaviy narx
b = 50

narx = X @ w + b

print(f"uy narxlari: {narx} mln so'm ekan")


uy narxlari: [ 690  910 1110 1330 1650] mln so'm ekan
